2019-01-06 11:11:48,450 - logs/Table.logs:15 - WARNING - logs/Table.logs
2019-01-06 12:46:12,040 - logs/Table.logs:15 - WARNING - logs/Table.logs
2019-01-06 12:47:44,080 - logs/Table.logs:15 - WARNING - logs/Table.logs
2019-01-06 12:52:47,748 - logs/Table.logs:15 - WARNING - logs/Table.logs
2019-01-06 12:54:04,286 - logs/Table.logs:15 - WARNING - logs/Table.logs
2019-01-06 13:57:12,685 - logs/Table.logs:15 - WARNING - logs/Table.logs
2019-01-06 13:59:28,149 - logs/Table.logs:15 - WARNING - logs/Table.logs
2019-01-06 14:03:42,584 - logs/Table.logs:15 - WARNING - logs/Table.logs
2019-01-06 14:07:05,289 - logs/Table.logs:15 - WARNING - logs/Table.logs
2019-01-06 14:20:04,729 - logs/Table.logs:15 - WARNING - logs/Table.logs
2019-01-06 14:20:05,251 - logs/Table.logs:29 - ERROR - Graph draw
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/clickhouse_streamer/scripts/tablemanager/Table.py", line 15, in Table
    cols = list(table_dict[table_alias].keys())
KeyError: 'transaction'
2019-01-06 14:21:04,607 - logs/Table.logs:15 - WARNING - logs/Table.logs
